language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.5
  - nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
