name = "UnixTimes"
uuid = "ab1a18e7-b408-4913-896c-624bb82ed7f4"
authors = ["Christian Rorvik <christian.rorvik@gmail.com>"]
version = "1.7.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[extensions]
UnixTimesMakieExt = ["Makie", "Observables"]
UnixTimesStructTypesExt = "StructTypes"
UnixTimesTimeZonesExt = "TimeZones"

[compat]
Makie = "0.22, 0.23, 0.24"
Observables = "0.5"
TimeZones = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[targets]
test = ["Test", "TimeZones"]
