name = "UnixTimes"
uuid = "ab1a18e7-b408-4913-896c-624bb82ed7f4"
authors = ["Christian Rorvik <christian.rorvik@gmail.com>"]
version = "1.5.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[extensions]
UnixTimesMakieExt = ["Makie", "MakieCore"]
UnixTimesTimeZonesExt = "TimeZones"

[compat]
TimeZones = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[targets]
test = ["Test", "TimeZones"]
